### ISSUE TITLE
Memmory mapping fails with large amounts of RAM

### ISSUE THREAD

**Issue by dpeter99** [TheCurle/Chroma#7]
**What went wrong?** 
Memory mapping fails if there are more than 40944 memory pages.

**How can we recreate the issue?**  
Step 1: Give the VM something like 512MB RAM
Step 2: Try to boot it.

**What do you think went wrong?**  
I think the last instruction in ``MapVirtualPageNoDirect`` might be writing to the actual program code meomory. As the function's return get's corrupted.

**Comment by TheCurle** [comment]
Solved by page-aligning the physical memory allocator.
It was giving us 0x4400 as the second batch, which when page-aligned is 0x4000, which is where the stack is!
It works up to 4GB now. More than that will error because it tries to fit all of it in the 3GB low buddy.
